# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76651a4f2ca618d369b99ad3661ec4785962e9b0e4f6abf9c8cf4faab9b5b58ccf17b4b6a7bb9a2a326bd74b540d62d250da113d35b207ec431df53d2df16d0a

test:
  secret_key_base: 0cf61615f803d898891ebac7de57e26aeb0bc03dcb490e3d707b8d4c59835e5e31fab348207ed460f210651021c20bd58493d2e6f92142ea5459259eb6c17366

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
